"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    q: "What is Pinnara.ai?",
    a: "Pinnara.ai is an AI-powered SEO tool that helps you create SEO-optimized blog content using advanced AI technology. It combines SEO, AEO, and GEO optimization to ensure your content ranks across Google, ChatGPT, and Perplexity.",
  },
  {
    q: "Is Pinnara.ai an SEO blog writer?",
    a: "Yes. Pinnara.ai is a full-featured SEO blog writer that generates structured, keyword-optimized long-form content with proper heading hierarchy, FAQ sections, and internal linking suggestions — all ready to publish.",
  },
  {
    q: "Does Pinnara.ai work as an SEO blog generator?",
    a: "Absolutely. Pinnara.ai functions as a powerful SEO blog generator that produces complete, publish-ready articles optimized for search engines. Just provide your topic and keywords, and get a fully structured blog post in minutes.",
  },
  {
    q: "Is Pinnara.ai good for Google rankings?",
    a: "Yes. Every piece of content generated by Pinnara.ai is optimized with on-page SEO best practices including keyword placement, heading structure, meta descriptions, FAQ schema, and E-E-A-T compliance to maximize your Google ranking potential.",
  },
  {
    q: "Can beginners use Pinnara.ai?",
    a: "Definitely. Pinnara.ai is designed for users of all skill levels. No technical SEO knowledge is required — the AI handles keyword optimization, content structuring, and image generation automatically.",
  },
];

export function LandingFAQ() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <div className="space-y-3 max-w-3xl mx-auto">
      {faqs.map((faq, i) => (
        <div
          key={i}
          className="border border-gray-100 rounded-2xl bg-white overflow-hidden transition-shadow hover:shadow-sm"
        >
          <button
            onClick={() => setOpen(open === i ? null : i)}
            className="w-full flex items-center justify-between px-6 py-5 text-left"
          >
            <span className="text-[15px] font-semibold text-gray-900">{faq.q}</span>
            <ChevronDown
              className={`w-5 h-5 text-gray-400 shrink-0 ml-4 transition-transform duration-200 ${
                open === i ? "rotate-180" : ""
              }`}
            />
          </button>
          <div
            className={`overflow-hidden transition-all duration-300 ${
              open === i ? "max-h-60 pb-5 px-6" : "max-h-0"
            }`}
          >
            <p className="text-sm text-gray-500 leading-relaxed">{faq.a}</p>
          </div>
        </div>
      ))}
    </div>
  );
}
